### ISSUE TITLE
All rights reversed

### ISSUE THREAD

**Issue by rugk** [neosmart/static-compress#1]
In the Readme you write "All rights reversed". However, as you use the MIT license, it is correcter to write "Some rights reserved" as you of course resign some rights as described in the MIT license.

**Comment by mqudsi** [comment]
You are correct. We normally use something along the lines of "XXX is released under the terms of the MIT public license, and any rights not accordingly conferred are reserved and copyright NeoSmart Technologies 2017."

I'll update the repo soon. Thanks for dropping by.
